version: 2
jobs:
  build:
    working_directory: ~/ex_abi
    docker:
      - image: elixir:latest
        environment:
          MIX_ENV: test
    steps:
      - checkout

      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache

      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get

      - run: mix credo
      - run: mix format --check-formatted
      - run: mix test

      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
